### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [MarciaOrr/firehose_splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by MarciaOrr** [comment]
I think that the addition you are looking for is
<meta='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>

It is placed inside <head> in application.html.erb.

If this is correct, I will push the change up to GitHub and Heroku. If not, I'll continue to research with another small hint from you.

**Comment by MarciaOrr** [comment]
I forgot the most important line above
<meta='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
